export const GET_NETFLIX_ORIGINAL='GET_NETFLIX_ORIGINAL';
export const GET_TOPRATED_MOVIES='GET_TOPRATED_MOVIES';
export const GET_ACTION_MOVIES='GET_ACTION_MOVIES';
export const GET_COMEDY_MOVIES='GET_COMEDY_MOVIES';
export const GET_ROMANCE_MOVIES='GET_ROMANCE_MOVIES';
export const GET_TRENDDING_MOVIES='GET_TRENDDING_MOVIES';
export const SET_MOVIE_DETAIL='SET_MOVIE_DETAIL';
export const GET_SEARCH_MOVIES='GET_TRENDDING_MOVIES';